# Generated by Django 3.2.13 on 2022-07-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_auto_20220705_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
    ]
