# Generated by Django 3.2.13 on 2022-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_remove_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img1',
            field=models.ImageField(default='bbbb', upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='img2',
            field=models.ImageField(default='cccc', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
